// THIS FILE WAS GENERATED BY "Binary Protocol Designer"
// Visit https://github.com/shkim/bpdtool for more information.
#pragma once

#define PROTOCOL_MAGIC			0x1234
#define PROTOCOL_VERSION		1

// END OF GENERATION
